import { StyleSheet, Platform } from 'react-native';
import { green, white, red, black } from '../utils/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  form:{
    backgroundColor: white,
    paddingTop: 40,
    paddingBottom: 40,
    paddingLeft: 10,
    paddingRight: 10,
    margin: 10,
    borderRadius: Platform.OS === 'ios' ? 7 : 2,
    shadowRadius: 3,
    shadowOpacity: 0.8,
    shadowColor: 'rgba(0, 0, 0, 0.24)',
    shadowOffset: {
      width: 0,
      height: 3
    },
  },
  title: {
    fontSize: 30,
    textAlign: 'center',
    margin: 10
  },
  subtitle: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
    marginBottom: 30,
  },
  input: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: Platform.OS === 'ios' ? 7 : 2,
    marginTop: 20,
    marginBottom: 30,
    paddingLeft:8,
    paddingRight:8,
  },
  iosSubmitBtn: {
    backgroundColor: green,
    padding: 10,
    borderRadius: 7,
    height: 45,
    marginLeft: 40,
    marginRight: 40,
    marginBottom: 30,
  },
  AndroidSubmitBtn: {
    backgroundColor: green,
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    height: 45,
    borderRadius: 2,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitBtnText: {
    color: white,
    fontSize: 22,
    textAlign: 'center',
  },
  iosSubmitBtnRed: {
    backgroundColor: red,
    padding: 10,
    borderRadius: 7,
    height: 45,
    marginLeft: 40,
    marginRight: 40,
    marginBottom: 30,
  },
  AndroidSubmitBtnRed: {
    backgroundColor: red,
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    height: 45,
    borderRadius: 2,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitBtnTextBlack: {
    color: black,
    fontSize: 22,
    textAlign: 'center',
  },
  iosSubmitBtnWhite: {
    backgroundColor: white,
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: 1,
    padding: 10,
    borderRadius: 7,
    borderColor: black,
    height: 50,
    marginLeft: 40,
    marginRight: 40,
    marginBottom: 30,
  },
  AndroidSubmitBtnWhite: {
    backgroundColor: white,
    flexDirection: 'row',
    justifyContent: 'center',
    borderColor: black,
    borderWidth: 1,
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    height: 50,
    borderRadius: 2,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitBtnTextBlack: {
    color: black,
    fontSize: 22,
    textAlign: 'center',
  },
  playIcon: {
    paddingLeft:16
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 30,
    marginRight: 30,
  },
  scrollView: {
    backgroundColor: white,
    margin: 25,
    marginBottom: 35,
    borderRadius: 7,
    borderColor: 'gray',
    borderWidth: 1,
  },
  itemScrollView: {
    margin: 0,
    borderBottomWidth: 1,
    borderColor: 'gray',
    paddingTop: 10,
    paddingBottom: 10,
    justifyContent: 'center',
  },
  textItemScrollView: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 25
  },
  cardBody: {
    minHeight: 200,
    marginTop: 0,
    justifyContent: 'center'
  },
});
